# Generated by Django 4.1.5 on 2023-01-16 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 16, 21, 2, 51, 215484, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
