# Generated by Django 4.1.5 on 2023-01-16 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 16, 21, 3, 49, 353404, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
